---
- name: Deploy
  hosts: all
  become: true

  vars_files:
    - roles/secure/vars/main.yml

  tasks:
    - name: Run server hardening tasks
      ansible.builtin.import_tasks: roles/secure/tasks/main.yml
