---
# Base server security settings

- name: Update APT cache if needed
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Update distribution
  ansible.builtin.apt:
    upgrade: dist

- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - fail2ban
    - unattended-upgrades

- name: Enable unattended upgrades
  ansible.builtin.template:
    src: "roles/secure/templates/{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - 20auto-upgrades

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Enable fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true

- name: Install UFW
  ansible.builtin.apt:
    name: ufw

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Configure UFW default policy
  community.general.ufw:
    default: "{{ ufw_default_policy }}"

- name: Configure logging
  community.general.ufw:
    logging: "{{ ufw_logging }}"

- name: Add UFW rules
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
  loop: "{{ ufw_rules }}"
  notify: restart ufw

- name: Disable root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "#PermitRootLogin"
    line: "PermitRootLogin no"
  notify: restart sshd
