- name: Create directory
  file:
    state: directory
    path: "{{ uptimekuma_path }}"
    mode: '0655'

- name: Copy compose.yml
  copy:
    src: "{{ compose_file_path }}"
    dest: "{{ uptimekuma_path }}"

- name: Run Docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ uptimekuma_path }}"

